version: '3'

services:
  database:
    container_name: nodes_db
    build:
      context: .
      dockerfile: "./db/Dockerfile"
    environment:
      - POSTGRES_PASSWORD=superuser_pwd
      - POSTGRES_DB=nodes
    volumes:
      - nodes_db_volume:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  nodes_db_volume:
